version: "3"
services:
  graph-node:
    image: graphprotocol/graph-node:v0.21.1
    ports:
      - "8100:8000"
      - "8101:8001"
      - "8120:8020"
      - "8130:8030"
      - "8140:8040"
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: matic:$RPC_ENDPOINT_MUMBAI
      RUST_LOG: info

  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - "5101:5001"
    volumes:
      - ./data-mumbai/ipfs:/data/ipfs

  postgres:
    image: postgres
    ports:
      - "25432:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - ./data-mumbai/postgres:/var/lib/postgresql/data
